
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2025 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_AXI_GPIO_BTN_DEVICE_ID,
		XPAR_AXI_GPIO_BTN_BASEADDR,
		XPAR_AXI_GPIO_BTN_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_BTN_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_SW_DEVICE_ID,
		XPAR_AXI_GPIO_SW_BASEADDR,
		XPAR_AXI_GPIO_SW_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_SW_IS_DUAL
	}
};


