# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/project_1_SMART_CON_0_0.xci
# IP: The module: 'project_1_SMART_CON_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/bd_fd52.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_0/bd_fd52_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_1/bd_fd52_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_2/bd_fd52_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_3/bd_fd52_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_4/bd_fd52_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_5/bd_fd52_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_6/bd_fd52_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_7/bd_fd52_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_8/bd_fd52_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_9/bd_fd52_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_10/bd_fd52_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_11/bd_fd52_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_12/bd_fd52_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_1/bd_fd52_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_1/bd_fd52_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_5/bd_fd52_s00a2s_0_ooc.xdc

# XDC: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_6/bd_fd52_sarn_0_ooc.xdc

# XDC: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_7/bd_fd52_srn_0_ooc.xdc

# XDC: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_8/bd_fd52_sawn_0_ooc.xdc

# XDC: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_9/bd_fd52_swn_0_ooc.xdc

# XDC: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_10/bd_fd52_sbn_0_ooc.xdc

# XDC: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_11/bd_fd52_m00s2a_0_ooc.xdc

# XDC: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'project_1_SMART_CON_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/project_1_SMART_CON_0_0.xci
# IP: The module: 'project_1_SMART_CON_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/bd_fd52.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_0/bd_fd52_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_1/bd_fd52_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_2/bd_fd52_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_3/bd_fd52_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_4/bd_fd52_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_5/bd_fd52_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_6/bd_fd52_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_7/bd_fd52_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_8/bd_fd52_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_9/bd_fd52_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_10/bd_fd52_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_11/bd_fd52_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_12/bd_fd52_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_1/bd_fd52_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_1/bd_fd52_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_5/bd_fd52_s00a2s_0_ooc.xdc

# XDC: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_6/bd_fd52_sarn_0_ooc.xdc

# XDC: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_7/bd_fd52_srn_0_ooc.xdc

# XDC: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_8/bd_fd52_sawn_0_ooc.xdc

# XDC: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_9/bd_fd52_swn_0_ooc.xdc

# XDC: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_10/bd_fd52_sbn_0_ooc.xdc

# XDC: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/bd_0/ip/ip_11/bd_fd52_m00s2a_0_ooc.xdc

# XDC: /tmp/tmp.JaCC5VtxSG/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_SMART_CON_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'project_1_SMART_CON_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
