# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/xdc/zc702.xdc

# XDC: imports/xdc/pl_zc702.xdc

# XDC: imports/xdc/default.xdc

# Block Designs: bd/project_1/project_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_1 || ORIG_REF_NAME==project_1} -quiet] -quiet

# IP: bd/project_1/ip/project_1_ZYNQPS_0_0/project_1_ZYNQPS_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_1_ZYNQPS_0_0 || ORIG_REF_NAME==project_1_ZYNQPS_0_0} -quiet] -quiet

# IP: bd/project_1/ip/project_1_AXI_GPIO_0_0/project_1_AXI_GPIO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_1_AXI_GPIO_0_0 || ORIG_REF_NAME==project_1_AXI_GPIO_0_0} -quiet] -quiet

# IP: bd/project_1/ip/project_1_PROC_SYS_RESET_0_0/project_1_PROC_SYS_RESET_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_1_PROC_SYS_RESET_0_0 || ORIG_REF_NAME==project_1_PROC_SYS_RESET_0_0} -quiet] -quiet

# IP: bd/project_1/ip/project_1_SMART_CON_0_0/project_1_SMART_CON_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_1_SMART_CON_0_0 || ORIG_REF_NAME==project_1_SMART_CON_0_0} -quiet] -quiet

# XDC: bd/project_1/project_1_ooc.xdc
